# Generated by Django 4.0.5 on 2023-06-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_transaccion_webpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='transaccion_webpay',
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('return_url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfilusuario')),
            ],
        ),
    ]
