# Generated by Django 4.0.5 on 2023-06-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_perfilusuario_transaccion_webpay_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaBeatpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('monto', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas_beatpay', to='core.perfilusuario')),
            ],
        ),
    ]
