# Generated by Django 4.0.5 on 2023-07-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_transferenciabeatpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciabeatpay',
            name='remitente',
        ),
        migrations.AddField(
            model_name='transferenciabeatpay',
            name='remitente_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciabeatpay',
            name='remitente_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
