# Generated by Django 4.0.5 on 2023-07-08 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_transferenciabeatpay_remitente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciabeatpay',
            name='remitente_id',
        ),
        migrations.RemoveField(
            model_name='transferenciabeatpay',
            name='remitente_type',
        ),
        migrations.AddField(
            model_name='transferenciabeatpay',
            name='remitente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas_beatpay', to='core.perfilusuario'),
            preserve_default=False,
        ),
    ]
