# Generated by Django 4.0.5 on 2023-07-08 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transferenciabeatpay_remitente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciabeatpay',
            name='remitente_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transferenciabeatpay',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas_beatpay', to='core.perfilusuario'),
        ),
    ]
