# Generated by Django 4.0.5 on 2023-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transferenciabeatpay_remitente_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciabeatpay',
            name='remitente_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
