# Generated by Django 4.0.5 on 2023-07-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transferenciabeatpay_remitente_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciabeatpay',
            name='remitente_str',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
